version: '3.8'

services:
  chatbot:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - WHATSAPP_API_TOKEN=${WHATSAPP_API_TOKEN}
      - WHATSAPP_PHONE_NUMBER_ID=${WHATSAPP_PHONE_NUMBER_ID}
      - WHATSAPP_BUSINESS_ACCOUNT_ID=${WHATSAPP_BUSINESS_ACCOUNT_ID}
      - WHATSAPP_WEBHOOK_VERIFY_TOKEN=${WHATSAPP_WEBHOOK_VERIFY_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CURSOS_SPREADSHEET_ID=${CURSOS_SPREADSHEET_ID}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - ./data/embeddings:/app/data/embeddings
      - ./scripts:/app/scripts
      - ./config:/app/config
      - ./models:/app/models
      - ./storage:/app/storage
      - ./utils:/app/utils
      - ./handlers:/app/handlers
      - ./services:/app/services
      - ./rag_system.py:/app/rag_system.py
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3